linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - funlen
    - godox
    - lll
    - maligned

issues:
  exclude-use-default: false
  exclude-rules:
    - path: rtptransceiverinit
      text: "type RtpTransceiverInit should be RTPTransceiverInit"
      linters:
        - stylecheck

run:
  skip-dirs-use-default: false
