linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable:
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace


run:
  skip-dirs-use-default: false
