linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - funlen

issues:
  exclude-use-default: false

run:
  skip-dirs-use-default: false
