#!/bin/sh

#
# DO NOT EDIT THIS FILE DIRECTLY
#
# It is automatically copied from https://github.com/pion/.goassets repository.
#

# Redirect output to stderr.
exec 1>&2

.github/lint-disallowed-functions-in-library.sh
