# SPDX-FileCopyrightText: 2026 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

FROM golang:1.27

RUN go install github.com/pion/webrtc/v5/examples/pion-to-pion/offer@latest

CMD ["offer"]
