#!/bin/bash
# Copyright 2018 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
# Modified work copyright 2019 Alex Browne.

# Check Node.js version
if [[ $(node --version) =~ v[0-9]\. ]]
then
	echo "Node.js version >= 10 is required"
	exit 1
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

NODE_WASM_EXEC="$(go env GOROOT)/misc/wasm/wasm_exec_node.js"
WASM_EXEC="$(go env GOROOT)/misc/wasm/wasm_exec.js"

if test -f "$NODE_WASM_EXEC"; then
	exec node --require="${DIR}/node_shim.js" "$NODE_WASM_EXEC" "$@"
else
	exec node --require="${DIR}/node_shim.js" "$WASM_EXEC" "$@"
fi


